import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HomeOutlinedIcon from "@mui/icons-material/HomeOutlined";
import BarChartRoundedIcon from "@mui/icons-material/BarChartRounded";
import AddCircleOutlineRoundedIcon from "@mui/icons-material/AddCircleOutlineRounded";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.className} text-gray-900`}>
        <div className="container mx-auto sm:px-6 lg:px-8 flex justify-center">
          <div className="w-full max-w-full sm:max-w-[600px] min-h-screen flex flex-col">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
